all:
  vars:
    control_plane_endpoint: 10.0.0.100
    load_balancer_ip_pool:
      - 10.0.0.0/27
metal:
  children:
    masters:
      hosts:
        metal1: {ansible_host: 10.0.1.110, mac: 'bc:24:11:a9:8a:34', disk: virtio0, network_interface: net0}
        metal2: {ansible_host: 10.0.1.111, mac: 'bc:24:11:56:0d:05', disk: virtio0, network_interface: net0}
        metal3: {ansible_host: 10.0.1.112, mac: 'bc:24:11:69:10:1b', disk: virtio0, network_interface: net0}
    workers:
      hosts:
        metal4: {ansible_host: 10.0.1.113, mac: 'bc:24:11:e9:01:f6', disk: virtio0, network_interface: net0}
